# Generated by Django 4.2.1 on 2024-04-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('CREATED', '생성됨'), ('DOWNLOADED', '다운로드됨')], default='CREATED')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '송금확인증',
                'db_table': 'certificate',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '유저',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers', to='certificates.user')),
            ],
            options={
                'verbose_name': '송금내역',
                'db_table': 'transfer',
            },
        ),
        migrations.CreateModel(
            name='CertificateTransferMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificate_transfers_maps', to='certificates.certificate')),
                ('transfer', models.ForeignKey(db_column='transfer_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificate_transfers_maps', to='certificates.transfer')),
            ],
            options={
                'verbose_name': '송금 확인증 매핑 테이블',
                'db_table': 'certificate_transfer_map',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificates', to='certificates.user'),
        ),
    ]
